# Generated by Django 4.2.7 on 2024-03-09 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
            ],
        ),
    ]
