# Generated by Django 4.2.7 on 2024-04-21 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaintsdepartmentrequests',
            name='request',
        ),
        migrations.RemoveField(
            model_name='electricitydepartmentrequests',
            name='request',
        ),
        migrations.RemoveField(
            model_name='engineeringdepartmentrequests',
            name='request',
        ),
        migrations.RemoveField(
            model_name='waterdepartmentrequests',
            name='request',
        ),
        migrations.AlterField(
            model_name='messages',
            name='ReadStatus',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='AdministrationDermentRequests',
        ),
        migrations.DeleteModel(
            name='ComplaintsDepartmentRequests',
        ),
        migrations.DeleteModel(
            name='ElectricityDepartmentRequests',
        ),
        migrations.DeleteModel(
            name='EngineeringDepartmentRequests',
        ),
        migrations.DeleteModel(
            name='WaterDepartmentRequests',
        ),
    ]
