# Generated by Django 4.2.7 on 2024-04-21 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_administrationdermentrequests_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaintsdepartmentrequests',
            name='requests_ptr',
        ),
        migrations.RemoveField(
            model_name='electricitydepartmentrequests',
            name='requests_ptr',
        ),
        migrations.RemoveField(
            model_name='engineeringdepartmentrequests',
            name='requests_ptr',
        ),
        migrations.RemoveField(
            model_name='waterdepartmentrequests',
            name='requests_ptr',
        ),
        migrations.DeleteModel(
            name='AdministrationDermentRequests',
        ),
        migrations.DeleteModel(
            name='ComplaintsDepartmentRequests',
        ),
        migrations.DeleteModel(
            name='ElectricityDepartmentRequests',
        ),
        migrations.DeleteModel(
            name='EngineeringDepartmentRequests',
        ),
        migrations.DeleteModel(
            name='WaterDepartmentRequests',
        ),
    ]
