# Generated by Django 4.2.7 on 2024-04-21 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0010_remove_complaintsdepartmentrequests_requests_ptr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrationDermentRequests',
            fields=[
                ('requests_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='page.requests')),
                ('Bill_Photo', models.BinaryField()),
                ('Rent_Photo', models.BinaryField()),
            ],
            bases=('page.requests',),
        ),
        migrations.CreateModel(
            name='ComplaintsDepartmentRequests',
            fields=[
                ('requests_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='page.requests')),
                ('Supportive_Photo', models.BinaryField()),
            ],
            bases=('page.requests',),
        ),
        migrations.CreateModel(
            name='ElectricityDepartmentRequests',
            fields=[
                ('requests_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='page.requests')),
                ('BuildingPermit_Photo', models.BinaryField()),
            ],
            bases=('page.requests',),
        ),
        migrations.CreateModel(
            name='EngineeringDepartmentRequests',
            fields=[
                ('requests_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='page.requests')),
                ('SpacePlan_Photo', models.BinaryField()),
                ('BuySellAgreement_Photo', models.BinaryField()),
                ('Ownership_Photo', models.BinaryField()),
                ('Geometricscheme_Photo', models.BinaryField()),
            ],
            bases=('page.requests',),
        ),
        migrations.CreateModel(
            name='WaterDepartmentRequests',
            fields=[
                ('requests_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='page.requests')),
                ('BuildingPermit_Photo', models.BinaryField()),
            ],
            bases=('page.requests',),
        ),
    ]
