# Generated by Django 4.2.7 on 2024-05-10 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0011_administrationdermentrequests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcements',
            name='Announcementsimage',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='Newsimage',
            field=models.BinaryField(null=True),
        ),
    ]
