# Generated by Django 4.2.7 on 2024-05-10 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0012_announcements_announcementsimage_news_newsimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricitydepartmentrequests',
            name='Oldsubscription_Photo',
            field=models.BinaryField(null=True),
        ),
    ]
