# Generated by Django 4.2.7 on 2024-05-10 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0013_electricitydepartmentrequests_oldsubscription_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterdepartmentrequests',
            name='Oldsubscription_Photo',
            field=models.BinaryField(null=True),
        ),
    ]
