# Generated by Django 4.2.7 on 2024-05-11 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0014_waterdepartmentrequests_oldsubscription_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='Status',
            field=models.TextField(),
        ),
    ]
