# Generated by Django 4.2.7 on 2024-05-11 04:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0016_alter_requests_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notices',
            fields=[
                ('NoticesID', models.AutoField(primary_key=True, serialize=False)),
                ('Details', models.TextField()),
                ('CitizenID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
