# Generated by Django 4.2.7 on 2024-05-11 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0017_notices'),
    ]

    operations = [
        migrations.AddField(
            model_name='notices',
            name='DueDate',
            field=models.DateTimeField(null=True),
        ),
    ]
