# Generated by Django 4.2.7 on 2024-05-11 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0018_notices_duedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='notices',
            name='ReadStatus',
            field=models.BooleanField(default=False),
        ),
    ]
