# Generated by Django 4.2.7 on 2024-05-13 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0019_notices_readstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='Type',
            field=models.TextField(null=True),
        ),
    ]
