# Generated by Django 4.2.7 on 2024-05-14 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0020_requests_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bills',
            old_name='Status',
            new_name='paid',
        ),
    ]
