# Generated by Django 4.2.7 on 2024-05-16 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0021_rename_status_bills_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricitydepartmentrequests',
            name='BuildingPermit_Photo',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='waterdepartmentrequests',
            name='BuildingPermit_Photo',
            field=models.BinaryField(null=True),
        ),
    ]
