# Generated by Django 4.2.7 on 2024-05-16 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0022_alter_electricitydepartmentrequests_buildingpermit_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineeringdepartmentrequests',
            name='CourtAffidavit_Photo',
            field=models.BinaryField(null=True),
        ),
    ]
