# Generated by Django 4.2.7 on 2024-05-16 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0023_engineeringdepartmentrequests_courtaffidavit_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engineeringdepartmentrequests',
            name='BuySellAgreement_Photo',
        ),
        migrations.AddField(
            model_name='engineeringdepartmentrequests',
            name='CertifiedEngineeringPlan_Photo',
            field=models.BinaryField(null=True),
        ),
    ]
