# Generated by Django 4.2.7 on 2024-05-16 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0024_remove_engineeringdepartmentrequests_buysellagreement_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineeringdepartmentrequests',
            name='Geometricscheme_Photo',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='engineeringdepartmentrequests',
            name='Ownership_Photo',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='engineeringdepartmentrequests',
            name='SpacePlan_Photo',
            field=models.BinaryField(null=True),
        ),
    ]
