# Generated by Django 4.2.7 on 2024-05-17 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0025_alter_engineeringdepartmentrequests_geometricscheme_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='Subscription_photo',
            field=models.BinaryField(null=True),
        ),
    ]
