# Generated by Django 4.2.7 on 2024-05-17 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0026_subscriptions_subscription_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='Name',
            field=models.TextField(null=True),
        ),
    ]
