# Generated by Django 4.2.7 on 2024-05-19 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0027_subscriptions_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='ID_Photo',
            field=models.BinaryField(null=True),
        ),
    ]
