from django.urls import path , include
from . import views

urlpatterns = [
    
    path('',views.homepage,name='homepage'),
    path('registration',views.registration,name='registration'),
    path('login',views.login,name='login'),
    path('registration_emploee' , views.registration_emploee , name = 'registration_emploee'),
    path('logout_view' , views.logout_view , name = 'logout_view'),
    path('Addressverification',views.Addressverification,name='Addressverification'),
    path('requests_table',views.requests_table,name='requests_table'),
    path('view_request/<int:requestid>/',views.view_request,name='view_request'),
    path('accounts_management',views.accounts_management,name='accounts_management'),
    path('citizens_accounts',views.citizens_accounts,name='citizens_accounts'),
    path('employee_accounts',views.employee_accounts,name='employee_accounts'),
    path('Updating_deleting_citizen',views.Updating_deleting_citizen,name='Updating_deleting_citizen'),
    path('Updating_deleting_employee',views.Updating_deleting_employee,name='Updating_deleting_employee'),
    path('updating_employee/<int:userid>/',views.updating_employee,name='updating_employee'),
    path('updating_citizen/<int:userid>/',views.updating_citizen,name='updating_citizen'),
    path('delete_employee/<int:userid>/',views.delete_employee,name='delete_employee'),
    path('news_announcements',views.news_announcements,name='news_announcements'),
    path('announcements',views.announcements,name='announcements'),
    path('news',views.news,name='news'),
    path('services',views.services,name='services'),
    path('service_details/<int:num>/<int:num1>/',views.service_details,name='service_details'),
    path('electricity_subscription/<int:num1>/',views.electricity_subscription,name='electricity_subscription'),
    path('Water_subscription/<int:num1>/',views.Water_subscription,name='Water_subscription'),
    path('delete_request/<int:requestid>/',views.delete_request,name='delete_request'),
    path('accept_request/<int:requestid>/',views.accept_request,name='accept_request'),
    path('Notice',views.Notice,name='Notice'),
    path('creat_bills/<int:requestid>/', views.creat_bills, name='creat_bills')  ,   
    path('bills',views.bills,name='bills'),
    path('accept_request/<int:requestid>/',views.accept_request,name='accept_request'),
    path('engineering_department_requests/<int:num1>/',views.engineering_department_requests,name='engineering_department_requests'),
    path('payments',views.payments,name='payments'),               
    path('Subscription/<int:requestid>/',views.Subscription,name='Subscription'),
    path('documents',views.documents,name='documents'), 
    path('news_and_announcements',views.news_and_announcements,name='news_and_announcements'), 
    path('complaints/<int:num1>/',views.complaints,name='complaints'),
    path('complaints_tabel',views.complaints_tabel,name='complaints_tabel'), 
    path('view_complaints/<int:requestid>/',views.view_complaints,name='view_complaints'),
    path('complaints_Done/<int:requestid>/',views.complaints_Done,name='complaints_Done'),
    path('payments_bill/<int:billid>/',views.payments_bill,name='payments_bill'),
    path('creat_notice/<int:requestid>/',views.creat_notice,name='creat_notice'),
    path('messages',views.messages,name='messages'), 
    path('create_message',views.create_message,name='create_message'),
    path('get_employees_by_department/<int:department_id>/', views.get_employees_by_department, name='get_employees_by_department'),
    path('about',views.about,name='about'),
    path('subscripions',views.subscripions,name='subscripions'),
]